# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22f8606b6a06ec28db5623c238ac01abed7c6ca701cbf86f1e1695fd5f171807e99e510bd0461f2e2ea5077ca783371607da2f7c343ca0622e8973c4886b1fb7

test:
  secret_key_base: 20f5e67708edda6fcfc3221409b6f7133b9398ffe837aa4b8d4ed6fea1981ba5a1cb57a9aefc3369527936ce5db24c5605e01a845d68487dbd26bef28c1066db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
